### ISSUE TITLE
New baseline - user that consents to all tracking

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/benchmarks#2]
- [ ] Prepare a special addon that automatically agrees to all tracking. It can likely be based on autconsent [example addon](https://github.com/duckduckgo/autoconsent/tree/main/addon)
- [ ] add a CLI option to load that addon instead of ghostery one

Additionally:
- [ ] add a CLI option to delete all profiles and measurements
